# Generated by Django 3.1.4 on 2020-12-09 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ac', 'Awaiting Checkout'), ('ap', 'Awaiting Payment'), ('p', 'Paid'), ('c', 'Cancelled'), ('f', 'Fullfiled')], default='ac', max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
